### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by beratkurar** [DIVA-DIA/LineSegmentationEvaluator#8]
Hi,

When I run the jar file, I am getting the following error due to the Pair class. Could you please help me? 

"Exception in thread "main" java.lang.NoClassDefFoundError: javafx/util/Pair
        at ch.unifr.LineSegmentationEvaluator.getMatchingPolygons(LineSegmentationEvaluator.java:409)
        at ch.unifr.LineSegmentationEvaluator.evaluate(LineSegmentationEvaluator.java:53)
        at ch.unifr.LineSegmentationEvaluatorTool.main(LineSegmentationEvaluatorTool.java:150)"

Thank you.

**Comment by lvoegtlin** [comment]
Hei,

I just freshly cloned the repo and used the jar in out/artifacts/ and this is working fine for me. 
Did you rebuild the jar based on the maven or do you use the stock one?

If you did change the code and rebuild it perhaps you have to change something in the maven (I do not have a lot of experience with maven).

Cheers

**Comment by beratkurar** [comment]
Thank you, Lars.
I did not change the code and I did not rebuild it.
I am using the stock one. 
Let me try the fresh jar in out/artifacts/ and going to inform what happens.

**Comment by beratkurar** [comment]
The freshly downloaded jar file raises the same error.
Do you have another suggestion?

**Comment by lvoegtlin** [comment]
What version of Java do you run it with? Do you use OpenJDK? As JavaFX was refactored out of the official built with version 9 I think.

**Comment by beratkurar** [comment]
The problem has been solved when the code is migrated to an old server with javafx.

**Comment by Nam-pfiev1995** [comment]
@beratkurar @lvoegtlin  Could you tell me the java or JavaFX version which you run correctly. I have same the problem when run the tool. For me, I used Java 8.

**Comment by beratkurar** [comment]
It worked on openjfx 11 and jdk 11.

**Comment by Nam-pfiev1995** [comment]
@beratkurar I just swap to Java 11 and openjfx 11 but the problem is still. Do I need fresh jar or something. 
 
![image](https://user-images.githubusercontent.com/72671625/135343720-8a7a6629-d7c7-4a2f-9f5e-436d8b7066b7.png)
and openjfx
![image](https://user-images.githubusercontent.com/72671625/135343834-de736a3c-289c-44ae-b791-8946331f8273.png)
Thanks in advance.

**Comment by beratkurar** [comment]
Sorry, I have written the previous answer based on the answer of my help desk. But here is what I have gather from the shell.

![image](https://user-images.githubusercontent.com/10862248/135387932-faf12e96-f0ac-4a48-ad8a-b08fb5e11e96.png)

**Comment by Nam-pfiev1995** [comment]
@beratkurar your version i think is  java 8. This is the same with my java 8. Normally, I can get the matching results in the console, but it can not show as the README.md file. I will try to reinstall java.
When you testing on DIVA-DB (i saw in two papers which you are the main author), did you get results on public or private test or both of them. Could we evaluate with this tool with sereval images (batch of image).
Thanks in advance.

**Comment by beratkurar** [comment]
I get results on the private test set.
Yes, we can run this code with a batch of images. [Here](https://github.com/beratkurar/diva_dataset_evaluate) is how I did.

**Comment by Nam-pfiev1995** [comment]
@beratkurar  Thanks for your answers and your code.

**Comment by FFrse** [comment]
Hi @beratkurar I downloaded DIVA-DB dataset and found there are two variations "all" and "all-privateTest", could you tell me the difference between the public set and the private set, which set should I use for performance comparison?
